### ISSUE TITLE
Cannot enable checkbox 

### ISSUE THREAD

**Issue by eunice0216** [Clockmender/Clockworx-Music#3]
![IMG_20210611_093608](https://user-images.githubusercontent.com/85714132/121618517-7bc13a00-ca99-11eb-94a4-f50567722077.jpg)

Hi, i have install the clockworx-music in blender 2.9.3. It has show up in user preferences but cannot enable the checkbox. May I know how to fix it?

**Comment by Clockmender** [comment]
Hello,

You have to install **PyGame Python library** as it says on the **README** in this page here:

https://github.com/Clockmender/Clockworx-Music

And repeated in the **Wiki - Install Page** here:

https://github.com/Clockmender/Clockworx-Music/wiki/01-Download-and-Installation

Then all should be fine and work well. I have tested it with 2.93 on Mac and have updated the install instructions to reflect the exact python version being used now. PyGame is used to access MIDI controllers by the way, so is necessary for the Live! MIDI functions and using controllers/keyboards to set parameters in the NodeTrees.

Let me know if you have any problems doing this.

Cheers Clock.

**Comment by eunice0216** [comment]
Hi Clock, i have try a few days to install PyGame Python library, but i have no idea. Could you teach me how to install? And where to find PyGame Python library

**Comment by Clockmender** [comment]
So, on a Mac you open a terminal and navigate to the Blender App:
type these commands and press return after each one:

cd /Applications

cd Blender.app/Contents/Resources/2.93/python/bin

./python3.9 -m ensurepip

./python3.9 -m pip install pygame

That does it for you! Pip will know where to get the file and will download and install it for you. It is vital that you use the local python file, you must put ./ in front of it or it will load the library into your **system** python area, Blender won't see that!

If you are on Windows, you need to find where the Blender python folder is.... It might be worth doing a search for *python39.exe* in your file browser - I never use Windows so can't really tell you...

This may be useful:

https://blenderartists.org/t/how-to-install-python-packages-with-pip-blender-2-8/1142721

You need to check the version number for Blender of course. This is in one of the posts, just adjust it for pygame:

<img width="790" alt="Screenshot 2021-06-14 at 13 38 17" src="https://user-images.githubusercontent.com/29657804/121893416-d961ba80-cd15-11eb-964b-40bacc562bf6.png">

It looks like the Blender file location on Windows is here:

**C:\Program Files\blender293\2.93\python\bin\** and is probably python39.exe.....

Try that, it may be you have to find it in your file browser.

**Comment by eunice0216** [comment]
thank you!
