### ISSUE TITLE
Installing PyGame - A generic, cross platform solution.

### ISSUE THREAD

**Issue by chiaravalle** [Clockmender/Clockworx-Music#4]
You can install pip modules from the Blender's Python console, by just writing 2 lines of code:

```
import pip (hit enter)
pip._internal.main(['install', 'pygame']) (hit enter)

```
Credits: https://stackoverflow.com/questions/12332975/installing-python-module-within-code
Tested on Blender 2.93 with Windows 10.

Cheers B)

**Comment by Clockmender** [comment]
Thank you, I will update the Wiki to this effect!

I do like this version:

``` python
import subprocess
import sys

try:
    import pygame as pg
except ImportError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", 'pygame'])
finally:
    import pygame as pg
```

Which presumably I could add to the scripts where PyGame is called or the ```__init.py__``` file? I'll have a play and see what happens...

Cheers, Clock.

PS. sorry for delay in replying...

**Comment by chiaravalle** [comment]
No problem for the delay. Yes, your version seems more appropriate, as it will install pygame the first time the AddOn is launched.

**Comment by Clockmender** [comment]
OK, pip is not installed in a new install...

So if I ensure pip first, it works, is there a way to ensure pip in the __init__.py file?

**Comment by chiaravalle** [comment]
Dunno, sorry.
I made the script after StackOverflow, but I know nothing about Python

**Comment by Clockmender** [comment]
No Problem, I'll play with it!

**Comment by Clockmender** [comment]
You do it like this:

```Python
import subprocess
import sys

try:
    import pip
except ImportError:
    subprocess.check_call([sys.executable, "-m", "ensurepip"])
try:
    import pygame as pg
except ImportError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", 'pygame'])
finally:
    import pygame as pg
```
